import { PrefixCommand } from "../../modules/commandutils";
import fetch from 'node-fetch'

export const gbruh = new PrefixCommand({
    names: ['gbruh'],
    bypassPause: false,
    adminOnly: true,
    action: async args => {
        var key = args.pch.prefix + args.name
        var searchArgs = args.message.content.substring(args.message.content.indexOf(key) + key.length).trim().split(' ').filter(str => str != "");
        var json = await gbSearch(searchArgs, 3)
        var str = json.map(entry => entry.file_url).reduce((allRows, nextRow) => allRows + "\n" + nextRow)
        args.message.channel.send(str)
    }
});










































//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!
//SERIOUS BRUH MOMENT ZONE, PROCEED WITH CAUTION. HIGH RISK OF CRINGE!!!



async function gbSearch(arr: string[], limit: number): Promise<{ file_url: string }[]> {
    var tagsString = "";
    arr.forEach(tag => {
        tagsString += tag + "+"
    })
    var response = await fetch(`https://gelbooru.com/index.php?page=dapi&s=post&q=index&json=1&api_key=69c6a9eec964e78c52f32440132168ea819e2b5947543ccce4589f487ad9ad09&user_id=731181&limit=${limit}&tags=${tagsString}` + tagsString)
    return await response.json();
}